PACKAGE_NAMES = dewi
TEST_PATHS ?= $(PACKAGE_NAMES)

#
# Don't need to change anything below this line
#

PYTHON ?= $(shell which python3)
PYTEST ?= $(PYTHON) -m pytest

REPORTS_DIR = doc/reports

PYCODESTYLE ?= $(PYTHON) -m pycodestyle
PYLINT ?= $(shell which pylint)

PYLINT_DIR = $(REPORTS_DIR)/pylint
PYLINT_OUTPUT = $(PYLINT_DIR)/pylint.out

BEHAVE ?= $(shell which behave) --format progress2
